spring.application.name=medical-clinic
# --- Postgres ---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/medical_clinic}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin}
# --- JPA ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
# --- Liquibase ---
spring.liquibase.contexts=dev
# --- Logi ---
logging.level.root=INFO
logging.level.com.samuelDawid.medical_clinic=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE